import Head from 'next/head'

import { NextPageWithLayout } from '../_app'

import { GetLayoutViewUserInfo } from '@/components/layout'
import { ViewUserInfo } from '@/modules/users-modules/view-user-info'

const UsersList: NextPageWithLayout = () => {
  return (
    <main className="w-full">
      <Head>
        <title>View User Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ViewUserInfo />
    </main>
  )
}

UsersList.getLayout = GetLayoutViewUserInfo
export default UsersList
