import Head from 'next/head'

import { NextPageWithLayout } from '../_app'

import { getGlobalLayout } from '@/components/layout'
import { UsersTable } from '@/modules/users-list/UsersTable'
const UsersList: NextPageWithLayout = () => {
  return (
    <main>
      <Head>
        <title>Users list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UsersTable />
    </main>
  )
}

UsersList.getLayout = getGlobalLayout
export default UsersList
