import Head from 'next/head'

import { NextPageWithLayout } from './_app'
import UsersList from './users'

import { getGlobalLayout } from '@/components/layout'

const Main: NextPageWithLayout = () => {
  return (
    <main className="w-full">
      <Head>
        <title>InctagramSuperAdmin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UsersList />
    </main>
  )
}

Main.getLayout = getGlobalLayout
export default Main
